name: Build and Test openplcproject

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install package
      run: |
        sudo apt-get -y install doxygen
        docker build .
        doxygen docs/doxygen.conf
